#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRD_FILE="$ROOT_DIR/prd.json"
PROMPT_FILE="$ROOT_DIR/ralph.md"
PROGRESS_FILE="$ROOT_DIR/progress.txt"

require_file() {
  local f="$1"
  if [[ ! -f "$f" ]]; then
    echo "Missing required file: $f" >&2
    exit 1
  fi
}

require_cmd() {
  local c="$1"
  if ! command -v "$c" >/dev/null 2>&1; then
    echo "Required command not found: $c" >&2
    exit 1
  fi
}

print_new_progress() {
  local start_line="$1"
  if [[ ! -f "$PROGRESS_FILE" ]]; then
    return
  fi

  local total_lines
  total_lines="$(wc -l < "$PROGRESS_FILE")"
  if [[ "$total_lines" -lt "$start_line" ]]; then
    return
  fi

  sed -n "${start_line},\$p" "$PROGRESS_FILE"
}

read_json() {
  local expr="$1"
  (
    cd "$ROOT_DIR"
    node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync('prd.json','utf8'));const r=($expr);if(r===undefined||r===null){process.exit(2)};if(typeof r==='object'){console.log(JSON.stringify(r));}else{console.log(String(r));}"
  )
}

require_file "$PRD_FILE"
require_file "$PROMPT_FILE"
require_cmd git
require_cmd node
require_cmd codex
require_cmd gh

echo "[ralph] Fetching latest remote refs"
git -C "$ROOT_DIR" fetch origin --prune

if [[ ! -f "$PROGRESS_FILE" ]]; then
  cat > "$PROGRESS_FILE" <<'EOF'
## Codebase Patterns
- Keep this section updated with reusable patterns discovered during implementation.

EOF
fi

if ! grep -q "^## Codebase Patterns" "$PROGRESS_FILE"; then
  tmp_file="$(mktemp)"
  {
    echo "## Codebase Patterns"
    echo "- Keep this section updated with reusable patterns discovered during implementation."
    echo
    cat "$PROGRESS_FILE"
  } > "$tmp_file"
  mv "$tmp_file" "$PROGRESS_FILE"
fi

progress_start_line=$(( $(wc -l < "$PROGRESS_FILE") + 1 ))

branch_prefix="$(read_json "d.branchPrefix ?? d.branchName ?? 'review'")"
if [[ -z "$branch_prefix" ]]; then
  echo "branchPrefix is missing in prd.json" >&2
  exit 1
fi

next_task_json="$(read_json "(() => { const isImplemented=t=>Boolean(t&&((typeof t.implemented==='boolean'&&t.implemented)||((typeof t.implemented!=='boolean')&&t.passes===true))); const tasks=(d.tasks||[]).filter(t=>t&&!isImplemented(t)).sort((a,b)=>(a.priority??1e9)-(b.priority??1e9)); return tasks[0]||null; })()")" || true

if [[ -z "${next_task_json:-}" || "$next_task_json" == "null" ]]; then
  echo "<promise>COMPLETE</promise>"
  exit 0
fi

task_id="$(node -e "const t=$next_task_json;console.log(t.id||'UNKNOWN');")"
task_title="$(node -e "const t=$next_task_json;console.log(t.title||'Untitled');")"
task_slug="$(node -e "const t=$next_task_json; const slug=String(t.title||'untitled').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').replace(/-+/g,'-').slice(0,48) || 'untitled'; console.log(slug);")"
branch_name="${branch_prefix}/${task_id,,}-${task_slug}"

echo "[ralph] Working on $task_id - $task_title"

current_branch="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD)"
base_ref="origin/main"
if [[ "$current_branch" == "${branch_prefix}/"* ]]; then
  base_ref="$current_branch"
fi

if [[ "$current_branch" != "$branch_name" ]]; then
  if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$branch_name"; then
    echo "[ralph] Checking out existing branch $branch_name"
    git -C "$ROOT_DIR" checkout "$branch_name"
    if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/remotes/origin/$branch_name"; then
      echo "[ralph] Rebasing $branch_name onto origin/$branch_name"
      git -C "$ROOT_DIR" rebase "origin/$branch_name"
    fi
  elif git -C "$ROOT_DIR" show-ref --verify --quiet "refs/remotes/origin/$branch_name"; then
    echo "[ralph] Checking out remote branch $branch_name"
    git -C "$ROOT_DIR" checkout -b "$branch_name" --track "origin/$branch_name"
  else
    echo "[ralph] Creating branch $branch_name from $base_ref"
    git -C "$ROOT_DIR" checkout -b "$branch_name" "$base_ref"
  fi
elif git -C "$ROOT_DIR" show-ref --verify --quiet "refs/remotes/origin/$branch_name"; then
  echo "[ralph] Rebasing current branch $branch_name onto origin/$branch_name"
  git -C "$ROOT_DIR" rebase "origin/$branch_name"
fi

tmp_prompt="$(mktemp)"
cat "$PROMPT_FILE" > "$tmp_prompt"
cat >> "$tmp_prompt" <<EOF

---

## Session Constraint (Generated by ralph_once.sh)

Implement exactly one feature this run:
- Feature ID: $task_id
- Feature Title: $task_title
- Feature Branch: $branch_name
- Feature JSON: $next_task_json

Rules for this run:
- Work only on this feature.
- Follow all instructions in ralph.md.
- Update prd.json: set only this feature's \`implemented\` to true when done.
- Never set \`accepted\`; that field is reserved for human review.
- Append an entry to progress.txt using the required format.
- If all features are implemented, output: <promise>COMPLETE</promise>
- Be terse in commentary and final output.
- Keep progress updates to at most 2 short sentences.
- Do not restate the task after starting.
- Do not explain routine file reads, searches, or obvious edits.
- Mention only blockers, implementation decisions, verification results, and concrete outcomes.
- Keep the final response under 6 lines unless there is a blocker or failed check that requires more detail.
EOF

set +e
echo "[ralph] Launching"
codex exec --full-auto -C "$ROOT_DIR" "$(cat "$tmp_prompt")"
codex_exit=$?
set -e
rm -f "$tmp_prompt"

print_new_progress "$progress_start_line"

if [[ $codex_exit -ne 0 ]]; then
  echo "Codex session exited with code $codex_exit" >&2
  exit "$codex_exit"
fi

git -C "$ROOT_DIR" push -u origin "$branch_name"

existing_pr_url="$(gh pr list --repo "$(git -C "$ROOT_DIR" remote get-url origin)" --head "$branch_name" --base main --state open --json url --jq '.[0].url' 2>/dev/null || true)"
if [[ -n "${existing_pr_url:-}" ]]; then
  echo "PR already open: $existing_pr_url"
else
  pr_body="$(cat <<EOF
Automated PR for $task_id - $task_title.

- Review the code changes on this branch
- Confirm the checks/statuses are acceptable
- Merge to \`main\` when approved
EOF
)"
  gh pr create \
    --repo "$(git -C "$ROOT_DIR" remote get-url origin)" \
    --base main \
    --head "$branch_name" \
    --title "[$task_id] $task_title" \
    --body "$pr_body"
fi

echo "Completed session for $task_id"
